apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cms
  namespace: cms
spec:
  ingressClassName: traefik
  rules:
    - host: cms.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
