apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golf
  namespace: golf
spec:
  ingressClassName: traefik
  rules:
    - host: golf.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: golf
                port:
                  number: 80
