apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sps-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jaosullivan/sps-crm
    targetRevision: devops/kan-8-eks-scaffold
    path: deploy/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
